###
http://localhost:3000/user/


###
GET http://localhost:3000/user


###
GET http://localhost:3000/user/12bef43a-3312-4225-a43f-c843abdfa55f

###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "testetoken",
    "email": "testetoken@gmail.com",
    "password": "token"
}

###
PATCH http://localhost:3000/user/847c44d7-f8ec-4e1a-ad12-255a7d608cad
Content-Type: application/json

{
    "email": "batatinhaTeste@gmail.com",
    "name": "batata",
    "password": "312"
}

###
DELETE http://localhost:3000/user/dff9a56c-0988-4fe2-9052-a1b028d9570a






###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "teste123@gmail.com", 
    "password": "teste123"
}

###
GET http://localhost:3000



###
POST http://localhost:3000/books/newbook
Content-Type: application/json

{
	"authors": "batatinha receitas2",
	"publication_date": 20230312,
	"description": "Receita de batata poh2",
	"genres": "Cozinha2",
	"publishing_company": "Cozinha para batatas2"
}



